# fly.toml app configuration file generated for club-connect on 2023-07-19T17:35:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "club-connect"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
